[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:auth-service]
command=/app/auth/auth-service
directory=/app/auth
environment=MIGRATIONS_DB_URL="%(ENV_AUTH_MIGRATIONS_DB_URL)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=30

[program:todo-service]
command=/app/todo/todo-service
directory=/app/todo
environment=MIGRATIONS_DB_URL="%(ENV_TODO_MIGRATIONS_DB_URL)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=30

[program:file-service]
command=/app/file/file-service
directory=/app/file
environment=MIGRATIONS_DB_URL="%(ENV_FILE_MIGRATIONS_DB_URL)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=30

[program:notification-service]
command=/app/notification/notification-service
directory=/app/notification
environment=MIGRATIONS_DB_URL="%(ENV_NOTIFICATION_MIGRATIONS_DB_URL)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=30

[program:scheduler-service]
command=/app/scheduler/scheduler-service
directory=/app/scheduler
environment=MIGRATIONS_DB_URL="%(ENV_SCHEDULER_MIGRATIONS_DB_URL)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=30
