name: auth-service

on:
  push:
    branches: [main]
    paths:
      - "auth-service/**"
      - ".github/workflows/auth-service.yml"
      - ".github/workflows/_go-service.yml"
  pull_request:
    branches: [main]
    paths:
      - "auth-service/**"
      - ".github/workflows/auth-service.yml"
      - ".github/workflows/_go-service.yml"

jobs:
  ci:
    uses: ./.github/workflows/_go-service.yml
    with:
      service: auth-service
      image: todo-auth-service
      port: "3000"
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
