name: notification-service

on:
  push:
    branches: [main]
    paths:
      - "notification-service/**"
      - ".github/workflows/notification-service.yml"
      - ".github/workflows/_go-service.yml"
  pull_request:
    branches: [main]
    paths:
      - "notification-service/**"
      - ".github/workflows/notification-service.yml"
      - ".github/workflows/_go-service.yml"

jobs:
  ci:
    uses: ./.github/workflows/_go-service.yml
    with:
      service: notification-service
      image: todo-notification-service
      port: "3003"
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
