name: todo-service

on:
  push:
    branches: [main]
    paths:
      - "todo-service/**"
      - ".github/workflows/todo-service.yml"
      - ".github/workflows/_go-service.yml"
  pull_request:
    branches: [main]
    paths:
      - "todo-service/**"
      - ".github/workflows/todo-service.yml"
      - ".github/workflows/_go-service.yml"

jobs:
  ci:
    uses: ./.github/workflows/_go-service.yml
    with:
      service: todo-service
      image: todo-todo-service
      port: "3001"
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
